/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./../src/view/components/ui/button/Button.vue')['default']
    ErrorBoundary: typeof import('./../src/view/components/features/ErrorBoundary.vue')['default']
    FormControl: typeof import('./../src/view/components/ui/form/FormControl.vue')['default']
    FormDescription: typeof import('./../src/view/components/ui/form/FormDescription.vue')['default']
    FormField: typeof import('vee-validate')['Field']
    FormItem: typeof import('./../src/view/components/ui/form/FormItem.vue')['default']
    FormLabel: typeof import('./../src/view/components/ui/form/FormLabel.vue')['default']
    FormMessage: typeof import('./../src/view/components/ui/form/FormMessage.vue')['default']
    InfiniteScroll: typeof import('./../src/view/components/features/InfiniteScroll.vue')['default']
    Input: typeof import('./../src/view/components/ui/input/Input.vue')['default']
    Label: typeof import('./../src/view/components/ui/label/Label.vue')['default']
    Loading: typeof import('./../src/view/components/ui/loading/Loading.vue')['default']
    RefreshControl: typeof import('./../src/view/components/features/RefreshControl.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sonner: typeof import('./../src/view/components/ui/sonner/Sonner.vue')['default']
    Tabs: typeof import('./../src/view/components/ui/tabs/Tabs.vue')['default']
    TabsContent: typeof import('./../src/view/components/ui/tabs/TabsContent.vue')['default']
    TabsList: typeof import('./../src/view/components/ui/tabs/TabsList.vue')['default']
    TabsTrigger: typeof import('./../src/view/components/ui/tabs/TabsTrigger.vue')['default']
  }
}
