/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./../src/view/components/ui/button/Button.vue')['default']
    Input: typeof import('./../src/view/components/ui/input/Input.vue')['default']
    Label: typeof import('./../src/view/components/ui/label/Label.vue')['default']
    Page: typeof import('./../src/view/components/features/Page.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
